# Generated by Django 3.0.5 on 2020-04-04 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^[0-9]{2}-[0-9]{3}$')])),
                ('coord_x', models.FloatField(blank=True, null=True)),
                ('coord_y', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('street', 'number', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=32)),
                ('address', models.PositiveIntegerField()),
                ('measurement', models.CharField(max_length=64)),
                ('unit', models.CharField(blank=True, max_length=8, null=True)),
                ('type', models.PositiveIntegerField(choices=[(1, 'INT'), (2, 'LONG'), (3, 'FLOAT')])),
                ('function_code', models.PositiveIntegerField(choices=[(3, 'READ_HOLDING_REGISTERS'), (4, 'READ_INPUT_REGISTERS')])),
                ('sf_address', models.PositiveIntegerField(blank=True, null=True)),
                ('sf_constant', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$')])),
                ('port', models.PositiveIntegerField()),
                ('slave_address', models.PositiveSmallIntegerField()),
                ('meter_id', models.CharField(max_length=32)),
                ('assigned', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=128)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
