# Generated by Django 3.0.5 on 2020-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coord_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='coord_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
