# Generated by Django 3.0.6 on 2020-05-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='chosenmeasurements',
            unique_together={('host', 'measurement')},
        ),
        migrations.AlterUniqueTogether(
            name='meter',
            unique_together={('name', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('meter', 'measurement')},
        ),
        migrations.RemoveField(
            model_name='register',
            name='sf_address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='sf_constant',
        ),
    ]
