# Generated by Django 3.0.5 on 2020-04-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meter',
            unique_together={('host', 'port', 'slave_address')},
        ),
    ]
