# Generated by Django 3.0.6 on 2020-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200512_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChosenMeasurements',
            new_name='AssignedMeasurement',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='id',
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
