# Generated by Django 3.0.5 on 2020-04-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200403_1250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('street', 'number', 'city')},
        ),
    ]
