# Generated by Django 3.0.5 on 2020-04-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200404_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nodes_connected',
            field=models.ManyToManyField(blank=True, related_name='_node_nodes_connected_+', to='management.Node'),
        ),
    ]
