# Generated by Django 3.0.5 on 2020-04-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200404_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='nodes_connected',
        ),
        migrations.AddField(
            model_name='node',
            name='nodes_connected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Node'),
        ),
    ]
